### ISSUE TITLE
Travis build attempts to download images for nodes

### ISSUE THREAD

**Issue by fbacall** [ElixirTeSS/TeSS#482]
During the seeding process

https://travis-ci.org/ElixirTeSS/TeSS/builds/274581718

```
Errno::ETIMEDOUT: Connection timed out - connect(2) for "www.ebi.ac.uk" port 80

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/paperclip-5.0.0/lib/paperclip/io_adapters/uri_adapter.rb:19:in `download_content'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/paperclip-5.0.0/lib/paperclip/io_adapters/uri_adapter.rb:7:in `initialize'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/paperclip-5.0.0/lib/paperclip/io_adapters/registry.rb:29:in `new'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/paperclip-5.0.0/lib/paperclip/io_adapters/registry.rb:29:in `for'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/paperclip-5.0.0/lib/paperclip/attachment.rb:100:in `assign'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/paperclip-5.0.0/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'

/home/travis/build/ElixirTeSS/TeSS/lib/tess/has_image.rb:34:in `resolve_image_url'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:432:in `block in make_lambda'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:164:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:164:in `block in halting'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `block in call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `each'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.9/lib/active_model/validations/callbacks.rb:113:in `run_validations!'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.9/lib/active_model/validations.rb:338:in `valid?'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/validations.rb:58:in `valid?'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/autosave_association.rb:324:in `association_valid?'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/autosave_association.rb:312:in `block in validate_collection_association'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/autosave_association.rb:312:in `each'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/autosave_association.rb:312:in `validate_collection_association'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/autosave_association.rb:217:in `block in define_autosave_validation_callbacks'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/autosave_association.rb:157:in `instance_eval'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:432:in `block in make_lambda'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:192:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:192:in `block in simple'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `block in call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `each'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.9/lib/active_model/validations.rb:399:in `run_validations!'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.9/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:117:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:117:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.9/lib/active_model/validations/callbacks.rb:113:in `run_validations!'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.9/lib/active_model/validations.rb:338:in `valid?'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/validations.rb:58:in `valid?'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/validations.rb:83:in `perform_validations'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/validations.rb:37:in `save'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/attribute_methods/dirty.rb:21:in `save'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:286:in `block (2 levels) in save'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:286:in `block in save'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:285:in `save'

/home/travis/build/ElixirTeSS/TeSS/app/models/node.rb:65:in `block in load_from_hash'

/home/travis/build/ElixirTeSS/TeSS/app/models/node.rb:53:in `map'

/home/travis/build/ElixirTeSS/TeSS/app/models/node.rb:53:in `load_from_hash'

/home/travis/build/ElixirTeSS/TeSS/db/seeds.rb:16:in `<top (required)>'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/railties-4.2.9/lib/rails/engine.rb:547:in `load_seed'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.9/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'

/home/travis/build/ElixirTeSS/TeSS/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'

/home/travis/.rvm/gems/ruby-2.2.6@global/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'

/home/travis/.rvm/gems/ruby-2.2.6@global/bin/bundle:23:in `load'

/home/travis/.rvm/gems/ruby-2.2.6@global/bin/bundle:23:in `<main>'

/home/travis/.rvm/gems/ruby-2.2.6@global/bin/ruby_executable_hooks:15:in `eval'

/home/travis/.rvm/gems/ruby-2.2.6@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fbacall** [comment]
It's the staff member avatar, not the node avatar
